name: Deploy to WordPress.org
on:
  push:
    tags:
      - "*"

jobs:
  tag:
    name: New tag
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master

    - name: Generate readme.txt
      uses: tarosky/workflows/actions/wp-readme@main

    - name: Build Release Zip
      run: |
        mkdir -p _build/avif-local-support
        grep -vE '^(#|$)' .distignore > .rsync_ignore
        rsync -rc --exclude-from=.rsync_ignore . _build/avif-local-support/
        cd _build
        zip -r ../avif-local-support.zip avif-local-support
        cd ..
        rm -rf _build

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: avif-local-support.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: WordPress Plugin Deploy
      uses: 10up/action-wordpress-plugin-deploy@stable
      env:
        SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
        SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
        SLUG: avif-local-support
